# Generated by Django 2.1.2 on 2018-10-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='member_type',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(default='Free', on_delete='PROTECT', to='membership.Membership'),
        ),
    ]
