# Generated by Django 2.1.2 on 2018-10-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20181023_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='Free', max_length=512),
        ),
    ]
