# Generated by Django 2.1.2 on 2018-12-13 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20181213_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='membership_start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 13, 8, 13, 50, 247463), null=True),
        ),
    ]
