# Generated by Django 2.1.2 on 2018-12-13 08:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20181213_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='membership_start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 13, 8, 15, 17, 296651, tzinfo=utc), null=True),
        ),
    ]
