# Generated by Django 2.1.2 on 2018-10-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('F', 'Free'), ('S', 'Silver'), ('G', 'Gold'), ('D', 'Diamond')], default='Free', max_length=100),
        ),
    ]
