# Generated by Django 2.1.2 on 2018-11-18 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20181023_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(default='Basic', on_delete=django.db.models.deletion.PROTECT, to='membership.Membership'),
        ),
    ]
