# Generated by Django 2.1.2 on 2018-12-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20181213_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='membership_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
