# Generated by Django 2.1.2 on 2018-11-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_membership_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
