# Generated by Django 2.1.2 on 2018-12-16 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20181213_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verify_time_limit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
