# Generated by Django 2.1.2 on 2018-12-07 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicVocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('word', models.CharField(max_length=150)),
                ('academic_in_sentence', models.CharField(max_length=300)),
                ('question_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='membership.Membership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnswerShortQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('audio', models.FileField(upload_to='ptebooster/media/answer-short-question')),
                ('item', models.CharField(max_length=90)),
                ('question_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='membership.Membership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dictation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('item', models.CharField(max_length=300)),
                ('audio', models.FileField(upload_to='ptebooster/media/dictation')),
                ('question_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='membership.Membership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('topic', models.TextField(max_length=1000)),
                ('question_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='membership.Membership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FillBlanksReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('option_1', models.CharField(max_length=150)),
                ('option_2', models.CharField(max_length=150)),
                ('option_3', models.CharField(max_length=150)),
                ('option_4', models.CharField(max_length=150)),
                ('option_5', models.CharField(blank=True, max_length=150)),
                ('option_6', models.CharField(blank=True, max_length=150)),
                ('answers', models.CharField(max_length=150)),
                ('paragraph', models.TextField(max_length=1000)),
                ('question_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='membership.Membership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FillInBlanks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('paragraph', models.TextField(max_length=1000)),
                ('audio', models.FileField(upload_to='ptebooster/media/fill-in-blanks')),
                ('answers', models.CharField(max_length=300)),
                ('question_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='membership.Membership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HighlightCorrectSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('option_1', models.TextField(max_length=500)),
                ('option_2', models.TextField(max_length=500)),
                ('option_3', models.TextField(max_length=500)),
                ('option_4', models.TextField(max_length=500)),
                ('answer', models.TextField(max_length=500)),
                ('paragraph', models.TextField(max_length=1000)),
                ('audio', models.FileField(upload_to='ptebooster/media/highlight-correct-summary')),
                ('question_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='membership.Membership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HighlightWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('paragraph', models.TextField(max_length=800)),
                ('audio', models.FileField(upload_to='ptebooster/media/highlight-incorrect-words')),
                ('answers', models.CharField(max_length=300)),
                ('correct_words', models.CharField(blank=True, max_length=300)),
                ('question_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='membership.Membership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('image_question', models.ImageField(upload_to='ptebooster/media/images', verbose_name='Image')),
                ('question_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='membership.Membership')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('module_name', models.CharField(max_length=80)),
                ('module_image', models.ImageField(default='ptebooster/media/icons/module_default.png', upload_to='ptebooster/media/icons')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='MultipleSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('paragraph', models.TextField(blank=True, max_length=600)),
                ('option_1', models.CharField(max_length=150)),
                ('option_2', models.CharField(max_length=150)),
                ('option_3', models.CharField(max_length=150)),
                ('option_4', models.CharField(max_length=150)),
                ('option_5', models.CharField(blank=True, max_length=150)),
                ('option_6', models.CharField(blank=True, max_length=150)),
                ('answers', models.CharField(max_length=150)),
                ('audio', models.FileField(upload_to='ptebooster/media/multiple-selection-listening')),
                ('question_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='membership.Membership')),
                ('related_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modules.Module')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultipleSelectionReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('option_1', models.CharField(max_length=150)),
                ('option_2', models.CharField(max_length=150)),
                ('option_3', models.CharField(max_length=150)),
                ('option_4', models.CharField(max_length=150)),
                ('option_5', models.CharField(blank=True, max_length=150)),
                ('option_6', models.CharField(blank=True, max_length=150)),
                ('answers', models.CharField(max_length=150)),
                ('paragraph', models.TextField(max_length=1000)),
                ('question_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='membership.Membership')),
                ('related_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modules.Module')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionSection',
            fields=[
                ('question_type', models.CharField(choices=[('Listening', 'Listening'), ('Reading', 'Reading'), ('Speaking', 'Speaking'), ('Writing', 'Writing')], max_length=15, primary_key=True, serialize=False)),
                ('module_image', models.ImageField(default='ptebooster/media/images/module_default.png', upload_to='ptebooster/media/section/images')),
            ],
        ),
        migrations.CreateModel(
            name='ReadTAloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('paragraph', models.TextField(max_length=1000)),
                ('audio', models.FileField(blank=True, upload_to='ptebooster/media/read-aloud')),
                ('question_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='membership.Membership')),
                ('related_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modules.Module')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReorderParagraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('option_1', models.TextField(max_length=500)),
                ('option_2', models.TextField(max_length=500)),
                ('option_3', models.TextField(max_length=500)),
                ('option_4', models.TextField(max_length=500)),
                ('answer', models.TextField(max_length=500)),
                ('option_5', models.TextField(max_length=500)),
                ('question_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='membership.Membership')),
                ('related_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modules.Module')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RepeatSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('item', models.CharField(max_length=300)),
                ('audio', models.FileField(upload_to='ptebooster/media/sentences')),
                ('question_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='membership.Membership')),
                ('related_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modules.Module')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RetellLecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('lecture', models.TextField(blank=True, max_length=1000)),
                ('audio', models.FileField(blank=True, upload_to='ptebooster/media/retell-lecture')),
                ('video', models.FileField(blank=True, upload_to='ptebooster/media/retell-lecture')),
                ('image', models.FileField(blank=True, upload_to='ptebooster/media/retell-lecture')),
                ('question_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='membership.Membership')),
                ('related_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modules.Module')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SelectMissingWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('option_1', models.TextField(max_length=500)),
                ('option_2', models.TextField(max_length=500)),
                ('option_3', models.TextField(max_length=500)),
                ('option_4', models.TextField(max_length=500)),
                ('answer', models.TextField(max_length=500)),
                ('audio_topic', models.CharField(max_length=100)),
                ('audio', models.FileField(upload_to='ptebooster/media/select-missing-word')),
                ('question_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='membership.Membership')),
                ('related_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modules.Module')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Spelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('item', models.CharField(max_length=100)),
                ('audio', models.FileField(upload_to='ptebooster/media/spelling-audio')),
                ('question_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='membership.Membership')),
                ('related_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modules.Module')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SummarizeSpokenText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('paragraph', models.TextField(max_length=1000)),
                ('audio', models.FileField(upload_to='ptebooster/media/summarize-spoken-text')),
                ('model_answer', models.TextField(blank=True, max_length=1000)),
                ('question_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='membership.Membership')),
                ('related_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modules.Module')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SummarizeWrittenText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('paragraph', models.TextField(max_length=1000)),
                ('model_answer', models.TextField(blank=True, max_length=1000)),
                ('question_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='membership.Membership')),
                ('related_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modules.Module')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='module',
            name='question_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='modules.QuestionSection'),
        ),
        migrations.AddField(
            model_name='images',
            name='related_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modules.Module'),
        ),
        migrations.AddField(
            model_name='highlightwords',
            name='related_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modules.Module'),
        ),
        migrations.AddField(
            model_name='highlightcorrectsummary',
            name='related_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modules.Module'),
        ),
        migrations.AddField(
            model_name='fillinblanks',
            name='related_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modules.Module'),
        ),
        migrations.AddField(
            model_name='fillblanksreading',
            name='related_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modules.Module'),
        ),
        migrations.AddField(
            model_name='essay',
            name='related_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modules.Module'),
        ),
        migrations.AddField(
            model_name='dictation',
            name='related_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modules.Module'),
        ),
        migrations.AddField(
            model_name='answershortquestions',
            name='related_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modules.Module'),
        ),
        migrations.AddField(
            model_name='academicvocabulary',
            name='related_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modules.Module'),
        ),
    ]
