# Generated by Django 2.1.2 on 2018-12-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicvocabulary',
            old_name='word',
            new_name='component_1',
        ),
        migrations.AddField(
            model_name='academicvocabulary',
            name='addition_1',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='academicvocabulary',
            name='addition_2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='academicvocabulary',
            name='component_2',
            field=models.CharField(default='a', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academicvocabulary',
            name='pos_1',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='academicvocabulary',
            name='pos_2',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='academicvocabulary',
            name='academic_in_sentence',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
