# Generated by Django 2.1.2 on 2018-12-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_auto_20181207_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicvocabulary',
            name='pos_1',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='academicvocabulary',
            name='pos_2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
