# Generated by Django 2.1.2 on 2018-12-07 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_auto_20181207_0532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicvocabulary',
            options={'ordering': ['component_1']},
        ),
        migrations.AlterUniqueTogether(
            name='academicvocabulary',
            unique_together={('component_1', 'component_2')},
        ),
    ]
