# Generated by Django 2.1 on 2018-08-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='module',
            name='module_image',
            field=models.ImageField(default='ptebooster/media/images/module_default.png', upload_to='ptebooster/media/images'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_question',
            field=models.ImageField(upload_to='ptebooster/media/images', verbose_name='Image'),
        ),
    ]
