# Generated by Django 2.1 on 2018-08-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_auto_20180816_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('audio', models.FileField(upload_to='ptebooster/media/spelling-audio')),
            ],
        ),
    ]
