# Generated by Django 2.1.2 on 2018-12-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_auto_20181207_0644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answershortquestions',
            old_name='item',
            new_name='question',
        ),
        migrations.AddField(
            model_name='answershortquestions',
            name='answer',
            field=models.CharField(default='a', max_length=90),
            preserve_default=False,
        ),
    ]
