# Generated by Django 2.1 on 2018-08-17 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0007_repeatsentence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repeatsentence',
            old_name='sentence_audio',
            new_name='audio',
        ),
    ]
