# Generated by Django 2.1.2 on 2018-12-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0008_auto_20181210_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='retelllecture',
            name='model_answer',
            field=models.FileField(blank=True, upload_to='ptebooster/media/retell-lecture'),
        ),
        migrations.AlterField(
            model_name='highlightcorrectsummary',
            name='answer',
            field=models.TextField(help_text='Enter answers with numbers separated with comman such as 1,2,3', max_length=500),
        ),
        migrations.AlterField(
            model_name='reorderparagraph',
            name='answer',
            field=models.TextField(help_text='Enter answers with numbers separated with comman such as 1,2,3', max_length=500),
        ),
        migrations.AlterField(
            model_name='retelllecture',
            name='audio',
            field=models.FileField(upload_to='ptebooster/media/retell-lecture'),
        ),
        migrations.AlterField(
            model_name='selectmissingword',
            name='answer',
            field=models.TextField(help_text='Enter answers with numbers separated with comman such as 1,2,3', max_length=500),
        ),
    ]
