# Generated by Django 2.1.2 on 2018-12-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0009_auto_20181212_0423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='image_question',
            new_name='image',
        ),
        migrations.AddField(
            model_name='images',
            name='model_answer_audio',
            field=models.FileField(blank=True, upload_to='ptebooster/media/retell-lecture'),
        ),
        migrations.AddField(
            model_name='images',
            name='model_answer_text',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
