# Generated by Django 2.1 on 2018-08-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0010_dictation'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField(max_length=800)),
                ('audio', models.FileField(upload_to='ptebooster/media/highlight-incorrect-words')),
                ('answers', models.CharField(max_length=300)),
                ('correct_words', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
