# Generated by Django 2.1.2 on 2018-12-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0010_auto_20181212_0733'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='questionsection',
            index=models.Index(fields=['question_type'], name='section_type_idx'),
        ),
    ]
