# Generated by Django 2.1.2 on 2018-12-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0011_auto_20181213_0541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['-module_name']},
        ),
        migrations.AddIndex(
            model_name='images',
            index=models.Index(fields=['image', 'model_answer_text', 'model_answer_audio'], name='images_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['active', 'module_name', 'question_type'], name='module_idx'),
        ),
        migrations.AddIndex(
            model_name='spelling',
            index=models.Index(fields=['item', 'audio'], name='spelling_idx'),
        ),
    ]
