# Generated by Django 2.1 on 2018-08-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0011_highlightwords'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectMissingWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_topic', models.CharField(max_length=100)),
                ('audio', models.FileField(upload_to='ptebooster/media/select-missing-word')),
                ('option_1', models.CharField(max_length=60)),
                ('option_2', models.CharField(max_length=60)),
                ('option_3', models.CharField(max_length=60)),
                ('option_4', models.CharField(max_length=60)),
                ('answer', models.CharField(max_length=60)),
            ],
        ),
    ]
