# Generated by Django 2.1 on 2018-08-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0012_selectmissingword'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightCorrectSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.CharField(max_length=1000)),
                ('audio', models.FileField(upload_to='ptebooster/media/highlight-correct-summary')),
                ('option_1', models.CharField(max_length=500)),
                ('option_2', models.CharField(max_length=500)),
                ('option_3', models.CharField(max_length=500)),
                ('option_4', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=500)),
            ],
        ),
    ]
