# Generated by Django 2.1.2 on 2018-12-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0012_auto_20181213_0546'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dictation',
            index=models.Index(fields=['item', 'audio'], name='dictation_idx'),
        ),
    ]
