# Generated by Django 2.1 on 2018-08-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0013_highlightcorrectsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadTAloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField(max_length=1000)),
                ('audio', models.FileField(blank=True, upload_to='ptebooster/media/read-aloud')),
            ],
        ),
        migrations.CreateModel(
            name='RetellLecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.TextField(blank=True, max_length=1000)),
                ('audio', models.FileField(blank=True, upload_to='ptebooster/media/retell-lecture')),
                ('video', models.FileField(blank=True, upload_to='ptebooster/media/retell-lecture')),
                ('image', models.FileField(blank=True, upload_to='ptebooster/media/retell-lecture')),
            ],
        ),
        migrations.AlterField(
            model_name='highlightcorrectsummary',
            name='answer',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='highlightcorrectsummary',
            name='option_1',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='highlightcorrectsummary',
            name='option_2',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='highlightcorrectsummary',
            name='option_3',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='highlightcorrectsummary',
            name='option_4',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='highlightcorrectsummary',
            name='paragraph',
            field=models.TextField(max_length=1000),
        ),
    ]
