# Generated by Django 2.1.2 on 2018-12-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0013_auto_20181213_0742'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='images',
            name='images_idx',
        ),
        migrations.AddIndex(
            model_name='images',
            index=models.Index(fields=['id', 'related_module', 'active', 'question_group'], name='images_idx'),
        ),
    ]
