# Generated by Django 2.1.2 on 2018-12-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0015_auto_20181213_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsection',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
