# Generated by Django 2.1 on 2018-08-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0015_essay'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillInBlanks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField(max_length=1000)),
                ('audio', models.FileField(upload_to='ptebooster/media/fill-in-blanks')),
                ('answers', models.CharField(max_length=300)),
            ],
        ),
    ]
