# Generated by Django 2.1 on 2018-08-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0016_fillinblanks'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerShortQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='ptebooster/media/answer-short-question')),
                ('answer', models.CharField(max_length=90)),
            ],
        ),
    ]
