# Generated by Django 2.1 on 2018-08-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0017_answershortquestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReorderParagraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_1', models.CharField(max_length=150)),
                ('sentence_2', models.CharField(max_length=150)),
                ('sentence_3', models.CharField(max_length=150)),
                ('sentence_4', models.CharField(max_length=150)),
                ('sentence_5', models.CharField(max_length=150)),
                ('answer', models.CharField(max_length=150)),
            ],
        ),
    ]
