# Generated by Django 2.1 on 2018-08-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0019_multipleselection'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleSelectionReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField(max_length=600)),
                ('option_1', models.CharField(max_length=150)),
                ('option_2', models.CharField(max_length=150)),
                ('option_3', models.CharField(max_length=150)),
                ('option_4', models.CharField(max_length=150)),
                ('option_5', models.CharField(blank=True, max_length=150)),
                ('option_6', models.CharField(blank=True, max_length=150)),
                ('answers', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='multipleselection',
            name='audio',
            field=models.FileField(upload_to='ptebooster/media/multiple-selection-listening'),
        ),
    ]
