# Generated by Django 2.1 on 2018-08-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0020_auto_20180822_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillBlanksReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField(max_length=1000)),
                ('answers', models.CharField(max_length=150)),
                ('option_1', models.CharField(max_length=150)),
                ('option_2', models.CharField(max_length=150)),
                ('option_3', models.CharField(max_length=150)),
                ('option_4', models.CharField(max_length=150)),
                ('option_5', models.CharField(blank=True, max_length=150)),
                ('option_6', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='multipleselectionreading',
            name='paragraph',
            field=models.TextField(max_length=1000),
        ),
    ]
