# Generated by Django 2.1 on 2018-08-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0023_summarizewrittentext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reorderparagraph',
            old_name='sentence_1',
            new_name='option_5',
        ),
        migrations.RemoveField(
            model_name='reorderparagraph',
            name='sentence_2',
        ),
        migrations.RemoveField(
            model_name='reorderparagraph',
            name='sentence_3',
        ),
        migrations.RemoveField(
            model_name='reorderparagraph',
            name='sentence_4',
        ),
        migrations.RemoveField(
            model_name='reorderparagraph',
            name='sentence_5',
        ),
        migrations.AddField(
            model_name='reorderparagraph',
            name='option_1',
            field=models.TextField(default='Test', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reorderparagraph',
            name='option_2',
            field=models.TextField(default='Test', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reorderparagraph',
            name='option_3',
            field=models.TextField(default='Test', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reorderparagraph',
            name='option_4',
            field=models.TextField(default='Test', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reorderparagraph',
            name='answer',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='selectmissingword',
            name='answer',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='selectmissingword',
            name='option_1',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='selectmissingword',
            name='option_2',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='selectmissingword',
            name='option_3',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='selectmissingword',
            name='option_4',
            field=models.TextField(max_length=500),
        ),
    ]
