# Generated by Django 2.1 on 2018-08-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0025_images_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicvocabulary',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dictation',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='repeatsentence',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='spelling',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
