# Generated by Django 2.1 on 2018-08-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0027_auto_20180831_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='answershortquestions',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fillblanksreading',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fillinblanks',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='highlightcorrectsummary',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='highlightwords',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='multipleselection',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='multipleselectionreading',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='readtaloud',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reorderparagraph',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='retelllecture',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='selectmissingword',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='summarizespokentext',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='summarizewrittentext',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
