# Generated by Django 2.1 on 2018-08-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0029_auto_20180831_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicvocabulary',
            name='free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='answershortquestions',
            name='free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dictation',
            name='free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fillblanksreading',
            name='free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fillinblanks',
            name='free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='highlightcorrectsummary',
            name='free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='highlightwords',
            name='free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='images',
            name='free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='module',
            name='free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='multipleselection',
            name='free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='multipleselectionreading',
            name='free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='readtaloud',
            name='free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reorderparagraph',
            name='free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='repeatsentence',
            name='free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='retelllecture',
            name='free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='selectmissingword',
            name='free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='spelling',
            name='free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='summarizespokentext',
            name='free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='summarizewrittentext',
            name='free',
            field=models.BooleanField(default=True),
        ),
    ]
