# Generated by Django 2.1 on 2018-09-11 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0030_auto_20180831_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictation',
            old_name='sentence_example',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='repeatsentence',
            old_name='sentence_example',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='spelling',
            old_name='word',
            new_name='item',
        ),
    ]
