# Generated by Django 2.1.2 on 2018-10-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(choices=[('F', 'Free'), ('S', 'Silver'), ('G', 'Gold'), ('D', 'Diamond')], default='F', max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('is_active', models.CharField(default=True, max_length=100)),
                ('duration', models.IntegerField(default=3)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
