# Generated by Django 2.1.2 on 2018-12-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('member_type', models.CharField(choices=[('Basic', 'Basic'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Diamond', 'Diamond')], default='Basic', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('presedence', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('is_active', models.CharField(default=True, max_length=100)),
                ('duration', models.IntegerField(default=3)),
                ('image', models.ImageField(default='ptebooster/media/images/module_default.png', upload_to='ptebooster/media/membership')),
                ('total_listening_question', models.IntegerField(default=50)),
                ('total_reading_question', models.IntegerField(default=50)),
                ('total_speaking_question', models.IntegerField(default=50)),
                ('total_writing_question', models.IntegerField(default=50)),
            ],
            options={
                'ordering': ('price',),
            },
        ),
    ]
