# Generated by Django 2.1.2 on 2018-10-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ('price',)},
        ),
        migrations.RemoveField(
            model_name='membership',
            name='id',
        ),
        migrations.AlterField(
            model_name='membership',
            name='member_type',
            field=models.CharField(choices=[('F', 'Free'), ('S', 'Silver'), ('G', 'Gold'), ('D', 'Diamond')], default='F', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
