# Generated by Django 2.1.2 on 2018-10-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20181023_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='total_listening_question',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='membership',
            name='total_reading_question',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='membership',
            name='total_speaking_question',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='membership',
            name='total_writing_question',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='membership',
            name='member_type',
            field=models.CharField(choices=[('B', 'Basic'), ('S', 'Silver'), ('G', 'Gold'), ('D', 'Diamond')], default='Basic', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
