# Generated by Django 2.1.2 on 2018-11-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_auto_20181110_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='presedence',
            field=models.IntegerField(default=0),
        ),
    ]
