# Generated by Django 2.1.2 on 2018-11-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_membership_presedence'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='module_image',
            field=models.ImageField(default='ptebooster/media/images/module_default.png', upload_to='ptebooster/media/membership'),
        ),
    ]
