# Generated by Django 2.1.2 on 2018-11-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('value', models.CharField(max_length=500)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Payment Method Parameters',
                'db_table': 'payment_method_parameters',
            },
        ),
        migrations.CreateModel(
            name='PaymentGateways',
            fields=[
                ('name', models.CharField(choices=[('PP', 'Paypal'), ('ST', 'Stripe'), ('AM', 'Amazon')], max_length=15, primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('is_sandbox', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='optionparameters',
            name='payment_option',
            field=models.ForeignKey(on_delete='CASCADE', related_name='payment_opt', to='purchase.PaymentGateways'),
        ),
    ]
