# Generated by Django 2.1.2 on 2018-12-07 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('name', models.CharField(choices=[('PP', 'Paypal'), ('ST', 'Stripe'), ('AP', 'Amazon')], max_length=15, primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('is_sandbox', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GatewayParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('value', models.CharField(max_length=500)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='purchase.Gateway')),
            ],
            options={
                'verbose_name_plural': 'Payment Method Parameters',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('error', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('PR', 'Processing'), ('AP', 'Approved'), ('FA', 'Failed'), ('RE', 'Refunded')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchase.Gateway')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='params', to='purchase.Transaction')),
            ],
            options={
                'verbose_name_plural': 'Transaction Params',
            },
        ),
        migrations.AlterUniqueTogether(
            name='transactionparam',
            unique_together={('transaction', 'name')},
        ),
    ]
