# Generated by Django 2.1.2 on 2018-11-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('request_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('is_registered', models.BooleanField(default=False)),
                ('is_paid_member', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=1250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
