# Generated by Django 2.1.2 on 2018-12-06 04:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20181206_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='receiver_id',
            field=models.IntegerField(default=0, help_text='Enter user ID for a specific user. For bulk notification leave as it is.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
