# Generated by Django 2.1.2 on 2018-12-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=25)),
                ('video_url', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
