# Generated by Django 2.1.2 on 2018-12-07 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('order_status', models.CharField(choices=[('PE', 'Pending'), ('PR', 'Processing'), ('CO', 'Complete'), ('CA', 'Cancelled')], max_length=15)),
                ('payment_status', models.CharField(choices=[('PE', 'Pending'), ('AU', 'Authorized'), ('PA', 'Paid'), ('PR', 'Partially Refunded'), ('RE', 'Refunded'), ('VO', 'Void')], max_length=15)),
                ('order_number', models.CharField(max_length=100)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('membership_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='membership.Membership')),
            ],
        ),
    ]
