# Generated by Django 2.1.2 on 2018-11-12 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20181112_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
